services:
  xpra-desktop:
    build: 
      context: .
      args:
        - REPO_URL_1=${REPO_URL_1}
        - REPO_URL_2=${REPO_URL_2}
        - GIT_TOKEN=${GIT_TOKEN}
    container_name: ubuntu-desktop
    ports:
      # VNC access
      - "127.0.0.1:5901:5901"
      # RustDesk ports
      - "127.0.0.1:21115:21115"
      - "127.0.0.1:21116:21116"
    environment:
      - TZ=Asia/Singapore
      # RustDesk configuration
      - RUSTDESK_ID_SERVER=192.168.50.165:21116
      - RUSTDESK_KEY=eKx7Y31FSGZ+2F6fyXj9S7Z1QcIKbhSRZeJrW5AqSxc=
      - RUSTDESK_CUSTOM_ID=912345678  # Change this to your preferred 9-digit ID
    shm_size: "1g"
    restart: unless-stopped
    volumes:
      - ./home:/home/dev
      - ./workspace:/home/dev/workspace
      # RustDesk configuration persistence
      - ./rustdesk-config:/home/dev/.config/rustdesk
