services:
  xpra-desktop:
    build: 
      context: .
      args:
        - REPO_URL_1=${REPO_URL_1}
        - REPO_URL_2=${REPO_URL_2}
        - GIT_TOKEN=${GIT_TOKEN}
    container_name: xpra-desktop
    # Security: by default, bind ONLY to localhost on the host.
    # Access it via your WireGuard, SSH tunnel, or reverse proxy.
    ports:
      - "127.0.0.1:14500:14500"
    environment:
      - TZ=Asia/Singapore
      # Optional: tweak desktop scaling/clarity
      - XPRA_DPI=120
    shm_size: "1g"
    restart: unless-stopped
    # Persist your home and a shared workspace
    volumes:
      - ./home:/home/dev
      - ./workspace:/home/dev/workspace
    # Optional NVIDIA GPU acceleration (uncomment if you have it set up)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]
